<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Click here</name>
   <tag></tag>
   <elementGuidId>a7129e61-835a-4506-b09a-51945bccab0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='loginContinueLink']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#loginContinueLink</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#loginContinueLink</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>13e7f450-03cd-4f40-8d91-d4b268d1cba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>loginContinueLink</value>
      <webElementGuid>09ba5bef-6dfa-4db8-98a9-76c63a382c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://iammaster.winlen.us/realms/ItemOptixP2/login-actions/authenticate?client_id=ItemOptixAuthentication&amp;tab_id=wetxr-RHQMs&amp;client_data=eyJydSI6Imh0dHBzOi8vaXRlbW9wdGl4djJxYS53aW5sZW4udXMvIiwicnQiOiJjb2RlIiwicm0iOiJmcmFnbWVudCIsInN0IjoiNTBiMjY1OTYtMjExMC00NzdjLWEyNWQtMzRmZjFhOGFhYTRiIn0</value>
      <webElementGuid>18f48970-25b6-4f6c-ad5a-f65267bdfc6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Click here</value>
      <webElementGuid>a820f7f5-e976-4163-b919-9928f86235bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginContinueLink&quot;)</value>
      <webElementGuid>88fd8625-df75-4adb-9666-8cf9a5276e8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value></value>
      <webElementGuid>2e00f469-c7a6-490f-97ea-dc60d5085725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='instruction1']/a[2]</value>
      <webElementGuid>a3b468e5-7284-4f21-9678-b9151c9cd413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Click here')])[2]</value>
      <webElementGuid>f94d4c05-62ff-42c7-8aa0-0e779ff34cda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click here'])[1]/following::a[1]</value>
      <webElementGuid>1d9da1be-ec48-4c5d-8b77-7b1f860c32cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In'])[1]/following::a[2]</value>
      <webElementGuid>41702de9-0802-4833-bf24-79cf3ca07d6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://iammaster.winlen.us/realms/ItemOptixP2/login-actions/authenticate?client_id=ItemOptixAuthentication&amp;tab_id=wetxr-RHQMs&amp;client_data=eyJydSI6Imh0dHBzOi8vaXRlbW9wdGl4djJxYS53aW5sZW4udXMvIiwicnQiOiJjb2RlIiwicm0iOiJmcmFnbWVudCIsInN0IjoiNTBiMjY1OTYtMjExMC00NzdjLWEyNWQtMzRmZjFhOGFhYTRiIn0')]</value>
      <webElementGuid>c7eac5dd-7236-4bdb-9271-35295932dd35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>01a6bfd5-ac48-4284-b2bf-f851ea51631c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'loginContinueLink' and @href = 'https://iammaster.winlen.us/realms/ItemOptixP2/login-actions/authenticate?client_id=ItemOptixAuthentication&amp;tab_id=wetxr-RHQMs&amp;client_data=eyJydSI6Imh0dHBzOi8vaXRlbW9wdGl4djJxYS53aW5sZW4udXMvIiwicnQiOiJjb2RlIiwicm0iOiJmcmFnbWVudCIsInN0IjoiNTBiMjY1OTYtMjExMC00NzdjLWEyNWQtMzRmZjFhOGFhYTRiIn0' and (text() = 'Click here' or . = 'Click here')]</value>
      <webElementGuid>0a48884c-b1de-4196-892f-62e6a53e19e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
