<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Shipments</name>
   <tag></tag>
   <elementGuidId>533e8994-cc80-4a79-8593-97c541d14201</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div[2]/button[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Shipments&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>eb6ca84f-e1ba-40c2-b33c-af6b212feca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-4 rounded-t transition-colors duration-200 font-medium text-sm hover:bg-white hover:text-teal-600 hover:fill-[#008b8b] rounded-tl-[0.8em] rounded-tr-[0.8em] hover:h-[50px]</value>
      <webElementGuid>8ecbb05a-56aa-4b19-aa69-dfc017c97db7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shipments</value>
      <webElementGuid>8bb98fc6-2401-4ea3-9951-71ece329bf17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sticky z-50 top-0 w-full bg-[#008b8b] text-text-white font-semibold&quot;]/div[@class=&quot;flex items-center justify-between px-6 min-h-[60px]&quot;]/div[@class=&quot;mt-[10px] space-x-1 ml-5 sm:ml-10 md:ml-16 lg:ml-20 xl:ml-24 flex justify-start items-center w-full max-w-full&quot;]/button[@class=&quot;px-4 rounded-t transition-colors duration-200 font-medium text-sm hover:bg-white hover:text-teal-600 hover:fill-[#008b8b] rounded-tl-[0.8em] rounded-tr-[0.8em] hover:h-[50px]&quot;]</value>
      <webElementGuid>334069bd-b152-4c42-89b0-da90bb1b6f9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[2]/button[7]</value>
      <webElementGuid>bec5c9ea-e82c-4c4e-8f36-950f7fd3f455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Track Items'])[1]/following::button[1]</value>
      <webElementGuid>d03a6079-0c35-49b7-80c1-1deb4d15f778</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inventory'])[1]/following::button[2]</value>
      <webElementGuid>ae9fd840-8dc6-4253-bcba-0a2642793082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Orders'])[1]/preceding::button[1]</value>
      <webElementGuid>58c4db57-8ec7-4143-9bd6-b5fe247200c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CS'])[1]/preceding::button[2]</value>
      <webElementGuid>43208973-3742-432f-ba34-1e801903dfc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Shipments']/parent::*</value>
      <webElementGuid>678c7509-32ea-4292-bfb1-48a816038338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[7]</value>
      <webElementGuid>81213a9c-9daa-4c28-83a8-33c5269e4dc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Shipments' or . = 'Shipments')]</value>
      <webElementGuid>a59f3aa6-1b83-4857-b49c-2716233b8fb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
