<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Inventory</name>
   <tag></tag>
   <elementGuidId>de7dd1c9-5869-4bdb-a7e1-3565f0c71241</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div[2]/button[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Inventory&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>688d0025-4f77-44da-a990-c9a7c1ea26cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-4 rounded-t transition-colors duration-200 font-medium text-sm hover:bg-white hover:text-teal-600 hover:fill-[#008b8b] rounded-tl-[0.8em] rounded-tr-[0.8em] hover:h-[50px]</value>
      <webElementGuid>dba243f7-93cd-4953-b984-92b693766331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Inventory</value>
      <webElementGuid>13d80014-50c1-47fd-b974-06dfe21ec4eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sticky z-50 top-0 w-full bg-[#008b8b] text-text-white font-semibold&quot;]/div[@class=&quot;flex items-center justify-between px-6 min-h-[60px]&quot;]/div[@class=&quot;mt-[10px] space-x-1 ml-5 sm:ml-10 md:ml-16 lg:ml-20 xl:ml-24 flex justify-start items-center w-full max-w-full&quot;]/button[@class=&quot;px-4 rounded-t transition-colors duration-200 font-medium text-sm hover:bg-white hover:text-teal-600 hover:fill-[#008b8b] rounded-tl-[0.8em] rounded-tr-[0.8em] hover:h-[50px]&quot;]</value>
      <webElementGuid>62ab0ea8-36cc-4d11-a5e3-e87606f11ad8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[2]/button[5]</value>
      <webElementGuid>a8111a6e-d1ef-4caa-80f5-dab0b6ba4159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tasks'])[1]/following::button[1]</value>
      <webElementGuid>e597708e-3c5d-4016-b746-8908104900ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tagging'])[1]/following::button[2]</value>
      <webElementGuid>d9338219-6c1d-408e-953f-49173b5aeb4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Track Items'])[1]/preceding::button[1]</value>
      <webElementGuid>27a00982-5c6d-4b6b-9337-34f36ce445b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipments'])[1]/preceding::button[2]</value>
      <webElementGuid>e3508baf-a4b5-46de-9405-ec9451707e6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Inventory']/parent::*</value>
      <webElementGuid>de7bb936-0905-47cb-930c-f63d318d0459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[5]</value>
      <webElementGuid>48f99a57-b00b-4a34-8d27-c6242873a563</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Inventory' or . = 'Inventory')]</value>
      <webElementGuid>ccb24927-72f7-4569-b828-efc606ca1d00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
