<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Tagging</name>
   <tag></tag>
   <elementGuidId>375a285d-55ff-4def-8859-db778b30087e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div[2]/button[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Tagging&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2f7eb11e-e420-41a6-bda9-2421affc8213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-4 rounded-t transition-colors duration-200 font-medium text-sm hover:bg-white hover:text-teal-600 hover:fill-[#008b8b] rounded-tl-[0.8em] rounded-tr-[0.8em] hover:h-[50px]</value>
      <webElementGuid>e0a11b87-db72-4eaf-8bb6-9042fb323bde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tagging</value>
      <webElementGuid>4a39088b-6bf2-44cf-828c-588b4c658da7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sticky z-50 top-0 w-full bg-[#008b8b] text-text-white font-semibold&quot;]/div[@class=&quot;flex items-center justify-between px-6 min-h-[60px]&quot;]/div[@class=&quot;mt-[10px] space-x-1 ml-5 sm:ml-10 md:ml-16 lg:ml-20 xl:ml-24 flex justify-start items-center w-full max-w-full&quot;]/button[@class=&quot;px-4 rounded-t transition-colors duration-200 font-medium text-sm hover:bg-white hover:text-teal-600 hover:fill-[#008b8b] rounded-tl-[0.8em] rounded-tr-[0.8em] hover:h-[50px]&quot;]</value>
      <webElementGuid>fd6edc0f-039d-448f-b8d9-620bcebca62c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[2]/button[3]</value>
      <webElementGuid>db76fcfa-87eb-4bd4-84de-400b98e3c606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Counting'])[1]/following::button[1]</value>
      <webElementGuid>58e01cbb-5e12-4260-a262-647585d3a189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tasks'])[1]/preceding::button[1]</value>
      <webElementGuid>aa013eb4-2282-4bc5-a364-d9ec8eb98a67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inventory'])[1]/preceding::button[2]</value>
      <webElementGuid>0305f12c-9bb5-41e2-90ff-356815bc8386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tagging']/parent::*</value>
      <webElementGuid>73fe8301-bfa6-425c-8311-f8f3f26ccd60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>cda69a35-de06-4ca3-8515-6514486a0742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Tagging' or . = 'Tagging')]</value>
      <webElementGuid>f505b000-44ec-4f3e-9c87-e2cd9cdc14d7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
