<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_mastertagtest</name>
   <tag></tag>
   <elementGuidId>e21dcd95-1744-4c75-9dc4-67359f22f2d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='cell-clientId-30']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cell-clientId-30 >> internal:text=&quot;mastertagtest&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6b3219e5-2fa6-41f6-9514-bcfc7e558ef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>eLabel</value>
      <webElementGuid>521be31a-3ac0-4ac7-96dc-42645bcffaf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-[#F1FAFF] text-[#1873BC] h-8 rounded flex items-center justify-start p-2 mt-1 cursor-pointer</value>
      <webElementGuid>84896d24-ea52-44d5-9ea6-740b7e4b667f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c2e9fc92-038c-48e1-9e2a-58d24701a40b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ag-82-label</value>
      <webElementGuid>c64c04ad-54af-41d7-8b8e-11958776d49a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>mastertagtest</value>
      <webElementGuid>415ffeb0-115b-418c-b648-647656a348b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cell-clientId-30&quot;)/div[@class=&quot;bg-[#F1FAFF] text-[#1873BC] h-8 rounded flex items-center justify-start p-2 mt-1 cursor-pointer&quot;]</value>
      <webElementGuid>669ea21a-086b-411c-9fc3-b6a7a3630cc8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='cell-clientId-30']/div</value>
      <webElementGuid>639f40ed-4f33-4657-ad74-759a0bdca721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[3]/following::div[4]</value>
      <webElementGuid>440d860b-e9a4-4e1d-a805-1ca9668c0a10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='advanced'])[1]/following::div[7]</value>
      <webElementGuid>22886a56-82c6-48a9-a130-47d4681d1c89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='mastertagtest'])[2]/preceding::div[1]</value>
      <webElementGuid>f21aac63-b9b2-4f97-b91a-6a669d0fddc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[4]/preceding::div[3]</value>
      <webElementGuid>d8c98a27-af99-4d9c-b1e4-b66bbe96891b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='mastertagtest']/parent::*</value>
      <webElementGuid>eeb8356d-3186-4038-afa2-3a40c19ad617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/span/div</value>
      <webElementGuid>018e4c34-ea5c-484e-8907-dac86fae5bca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'mastertagtest' or . = 'mastertagtest')]</value>
      <webElementGuid>b2ab4acb-6783-468c-8858-a45eedc744fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ag-82-label']</value>
      <webElementGuid>2f1c878d-ecc8-40b4-acbb-32a3813d0fd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/main/div/div[2]/div[2]/div/div[3]/div[6]/div/div/form/div/div/div[4]/div/div[2]/div[2]/div/div/div</value>
      <webElementGuid>b81f755a-4322-48d2-acb7-0f5e2ddfb970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Select All)'])[1]/following::div[5]</value>
      <webElementGuid>576b0973-7157-4120-b8e2-e5404565c87d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/following::div[17]</value>
      <webElementGuid>f693da19-a6a4-4323-b99f-950bda4b1e25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div[2]/div/div/div</value>
      <webElementGuid>935e4fc9-7722-4e84-b839-e42df4a0476d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ag-82-label' and (text() = 'mastertagtest' or . = 'mastertagtest')]</value>
      <webElementGuid>7ed3667b-ee8d-4826-adf1-1f7126a4b80c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
