<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_00195-WEBSTER_NY</name>
   <tag></tag>
   <elementGuidId>ae25502c-5dd4-4fce-99ac-91604c913d7b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div[3]/div/div[2]/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;00195-WEBSTER_NY&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0990d978-aa87-48cb-94d3-8ba477129a6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-6 py-2 text-sm text-black font-medium hover:bg-gray-100 cursor-pointer w-full</value>
      <webElementGuid>b708d126-0674-40fa-89fd-ad16e404b31e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>00195-WEBSTER_NY</value>
      <webElementGuid>1c877479-6357-4ccb-9ee4-b156bbed7eb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sticky z-50 top-0 w-full bg-[#008b8b] text-text-white font-semibold&quot;]/div[@class=&quot;flex items-center justify-between px-6 min-h-[60px]&quot;]/div[@class=&quot;bg-blue flex items-center justify-between space-x-10 ml-[80px]&quot;]/div[@class=&quot;relative&quot;]/div[@class=&quot;absolute top-full left-0 mt-1 w-[250px] bg-white rounded-md shadow-lg z-50&quot;]/div[@class=&quot;max-h-48 overflow-y-auto overflow-x-hidden whitespace-nowrap scrollbar-thin scrollbar-thumb-gray-300 scrollbar-track-gray-100&quot;]/div[@class=&quot;px-6 py-2 text-sm text-black font-medium hover:bg-gray-100 cursor-pointer w-full&quot;]</value>
      <webElementGuid>4afc948a-4694-41ec-8d87-f1cdd1539cef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[3]/div/div[2]/div/div[2]</value>
      <webElementGuid>836b28ce-e929-4f69-91cc-650dcb2a6b79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Orders'])[1]/following::div[7]</value>
      <webElementGuid>5b9b009d-80c7-4bdd-976f-46eac501803b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shipments'])[1]/following::div[7]</value>
      <webElementGuid>323d2ba9-d115-46ec-96c6-d4e67b10cfde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Abhi-DC'])[1]/preceding::div[10]</value>
      <webElementGuid>bff52e00-de8a-48b0-875f-2a929449e901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AT-testStore'])[1]/preceding::div[11]</value>
      <webElementGuid>578547fc-f973-4945-b5f6-2f7faf841418</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='00195-WEBSTER_NY']/parent::*</value>
      <webElementGuid>f999f05c-e193-4882-acd2-bbb6bf2c83ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div[2]</value>
      <webElementGuid>67436e69-fc7f-4b81-9e79-1c7f399de6a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '00195-WEBSTER_NY' or . = '00195-WEBSTER_NY')]</value>
      <webElementGuid>ee6b6245-4ee9-4c0f-9fe9-e1980ea57397</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
