<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_CC Type_absolute w-4 h-4 border-2 borde_a712d9</name>
   <tag></tag>
   <elementGuidId>97d03aa2-9f31-4e85-8634-07c80ea3d06d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/div[2]/div/div[2]/div/div[3]/div/div[3]/div[3]/label/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.absolute.w-4.h-4.border-2.border-teal-600.bg-background-primary.rounded-full.transition-transform.transform.top-1.left-1.translate-x-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>label >> internal:has-text=/^Date$/ >> div >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fc420b01-4219-4a90-8285-070e72571df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute w-4 h-4 border-2 border-teal-600 bg-background-primary rounded-full transition-transform transform top-1 left-1 translate-x-0</value>
      <webElementGuid>599011a1-e551-4da1-b2a4-a099a2a878c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/div[@class=&quot;w-full h-full overflow-hidden&quot;]/div[@class=&quot;h-full w-full&quot;]/div[@class=&quot;flex flex-col&quot;]/div[@class=&quot;w-full bg-background-secondary h-[calc(100vh-185px)] py-2 px-5&quot;]/div[@class=&quot;p-4 w-full h-full bg-background-secondary&quot;]/div[@class=&quot;fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50&quot;]/div[@class=&quot;bg-background-primary rounded-lg w-96 shadow-lg&quot;]/div[@class=&quot;show-scrollbar px-4 pb-4 space-y-3 max-h-[500px] overflow-y-scroll&quot;]/div[@class=&quot;flex items-center min-w-[200px]&quot;]/label[@class=&quot;flex items-center cursor-pointer w-full&quot;]/div[@class=&quot;relative&quot;]/div[@class=&quot;w-10 h-6 border-2 border-teal-600 rounded-full transition-colors bg-gray-200&quot;]/div[@class=&quot;absolute w-4 h-4 border-2 border-teal-600 bg-background-primary rounded-full transition-transform transform top-1 left-1 translate-x-0&quot;]</value>
      <webElementGuid>cbac1ecf-d05d-431f-80f5-30e13b4eade8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div[2]/div/div[2]/div/div[3]/div/div[3]/div[3]/label/div/div/div</value>
      <webElementGuid>ceb24616-c1e3-420b-b913-ab9b0e56f557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/label/div/div/div</value>
      <webElementGuid>f4826ea3-fa4c-4a9c-bbec-f6951b3f4c87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
