<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_mastertagtest_1</name>
   <tag></tag>
   <elementGuidId>5531ef4e-fdc5-483e-841f-c3c03b5747f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ag-100-label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ag-100-label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Filter List&quot;i >> internal:text=&quot;mastertagtest&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f4099d7f-9b9b-4e98-bb17-6fb6be5251d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>eLabel</value>
      <webElementGuid>bf713822-81b2-469e-a217-97743e8e23c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ag-input-field-label ag-label ag-checkbox-label ag-label-ellipsis</value>
      <webElementGuid>e024b9f1-657e-4c4c-886c-4c1db012903e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>df6785ad-4408-4fdb-9a04-92d2bf2e7a52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ag-100-label</value>
      <webElementGuid>d8d13e7e-6ec8-487e-b1f0-242584923f56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>mastertagtest</value>
      <webElementGuid>c98da5b2-45fd-4b10-8dae-01c3295df495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ag-100-label&quot;)</value>
      <webElementGuid>53555c1f-08d1-4456-a718-d8c9e7dff734</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ag-100-label']</value>
      <webElementGuid>e222aa3b-fe20-401b-99ba-45c9cffb88a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/main/div/div[2]/div[2]/div/div[3]/div[6]/div/div/form/div/div/div[4]/div/div[2]/div[2]/div/div/div</value>
      <webElementGuid>e1e70fc1-2a34-4fbf-889c-167a68503a82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Select All)'])[1]/following::div[5]</value>
      <webElementGuid>4e4af086-b7b7-458f-aff7-a5ab5b97b451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/following::div[17]</value>
      <webElementGuid>0f415539-bacf-4d01-a233-4ff26e2cab72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div[2]/div/div/div</value>
      <webElementGuid>e60d5792-9284-4ca7-bad7-229b79145a93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'ag-100-label' and (text() = 'mastertagtest' or . = 'mastertagtest')]</value>
      <webElementGuid>d71820d5-4525-415f-9c7f-49f0ecaa757e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
