<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_IO_FARM_510</name>
   <tag></tag>
   <elementGuidId>ed0f52e3-ac45-44db-b3cb-9eecaf33f3d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div[3]/div/div[2]/div/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;IO_FARM_510&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>590b9717-491a-4752-9efa-768aa59b442f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-6 py-2 text-sm text-black font-medium hover:bg-gray-100 cursor-pointer w-full</value>
      <webElementGuid>1e9cb5fe-c15f-47c4-879a-56b226afc073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>IO_FARM_510</value>
      <webElementGuid>25461e55-8823-4728-823b-c4aa1e0708b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sticky z-50 top-0 w-full bg-[#008b8b] text-text-white font-semibold&quot;]/div[@class=&quot;flex items-center justify-between px-6 min-h-[60px]&quot;]/div[@class=&quot;bg-blue flex items-center justify-between space-x-10 ml-[80px]&quot;]/div[@class=&quot;relative&quot;]/div[@class=&quot;absolute top-full left-0 mt-1 w-[250px] bg-white rounded-md shadow-lg z-50&quot;]/div[@class=&quot;show-scrollbar max-h-48 overflow-y-auto overflow-x-hidden whitespace-nowrap&quot;]/div[@class=&quot;px-6 py-2 text-sm text-black font-medium hover:bg-gray-100 cursor-pointer w-full&quot;]</value>
      <webElementGuid>3b964697-c7f3-470b-ae4a-77246043e63a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div[3]/div/div[2]/div/div[3]</value>
      <webElementGuid>9e525ef9-da99-44c6-a67d-9b5fdc87b21f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IO_FARM_503'])[1]/following::div[1]</value>
      <webElementGuid>95a04e8a-ba12-4b7b-90b4-7778c73c3a3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Orders'])[1]/following::div[8]</value>
      <webElementGuid>f1bcdd2f-f4d8-4bf8-9238-10cbb4e1a8c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Site-1'])[1]/preceding::div[1]</value>
      <webElementGuid>5fe0fc56-bb60-478c-8d8e-89500deef19b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Site-6363'])[1]/preceding::div[2]</value>
      <webElementGuid>bc3e6ba8-8155-4c06-92ab-5ffc22b7b1be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='IO_FARM_510']/parent::*</value>
      <webElementGuid>964ac81e-1483-44a4-b1a8-5095df325072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div[3]</value>
      <webElementGuid>a1e7b2d0-d60d-405c-9e84-acb05e557af6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'IO_FARM_510' or . = 'IO_FARM_510')]</value>
      <webElementGuid>c501b7ba-736a-4d27-af26-6eb4ef2773b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
