<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__lastName</name>
   <tag></tag>
   <elementGuidId>196440f5-152f-43f0-94d2-5b5c34c39b9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='lastName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;lastName&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;lastName&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b92dfe5-45e7-4d6b-a87a-094627cfd12c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>da8cbc53-5e40-4875-beb6-557800024d50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lastName</value>
      <webElementGuid>436e470d-29ab-4ee2-b796-bffe60a2186c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>block w-full border border-gray-300 rounded-md shadow-sm p-3</value>
      <webElementGuid>0610b6fb-fced-4561-9c71-9cce6e0c2506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>w</value>
      <webElementGuid>6d843a05-91d5-4558-9475-28fad7490631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;min-h-screen&quot;]/main[1]/div[@class=&quot;w-full&quot;]/div[2]/div[@class=&quot;max-w-full bg-background-primary relative&quot;]/div[@class=&quot;fixed z-50 inset-0 bg-black bg-opacity-50 flex justify-center items-center&quot;]/div[@class=&quot;bg-white p-8 rounded-lg w-full max-w-6xl h-[90vh] flex flex-col overflow-y-auto&quot;]/form[@class=&quot;flex-1 flex flex-col&quot;]/div[@class=&quot;flex-1 space-y-6&quot;]/div[@class=&quot;grid grid-cols-2 gap-6&quot;]/div[4]/input[@class=&quot;block w-full border border-gray-300 rounded-md shadow-sm p-3&quot;]</value>
      <webElementGuid>24e7eaf7-6264-4ab5-bb67-ef567e1a1ba1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='lastName']</value>
      <webElementGuid>316552e1-e903-4451-bfd9-0edc46c9c3c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/main/div/div[2]/div/div[3]/div/form/div/div/div[4]/input</value>
      <webElementGuid>39989987-68cb-4caa-9443-7ecbdf5d48ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>dc6e8974-6c13-4f95-ba76-ae6b95cfb430</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'lastName']</value>
      <webElementGuid>f0b26ced-8eeb-4311-b6d1-410749893880</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
