<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Loading_ag-1732-input</name>
   <tag></tag>
   <elementGuidId>aeb8eaad-e608-4334-b3e6-c1d892e7fa96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ag-1732-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ag-1732-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Search...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4cd1a4e2-edc7-45b0-9a72-a5a2d4e7441d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>eInput</value>
      <webElementGuid>742ae469-f99a-461c-9c67-68ef80826578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ag-input-field-input ag-text-field-input</value>
      <webElementGuid>6995b66f-d899-41be-8ea4-df91ddf8f50a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fb6a06ac-8a39-4059-b25d-9e7cdf49662b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ag-1732-input</value>
      <webElementGuid>613f42ea-056b-4114-8038-16acb8fc1539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>25c66338-c204-47e7-b287-e1228548f062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search filter values</value>
      <webElementGuid>205aafb0-76fe-4ca9-8da4-53ed761b8b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search...</value>
      <webElementGuid>6a77c737-173c-4ab8-92d1-b53c2853ed24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ag-1732-input&quot;)</value>
      <webElementGuid>79b318aa-ffe3-4293-a24a-fe47c5b4a789</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ag-1732-input']</value>
      <webElementGuid>5a460551-0600-44c3-86a3-b332a8de8e34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myGrid']/div/div[3]/div[6]/div/div/form/div/div/div[2]/div[2]/input</value>
      <webElementGuid>d3a16df4-7b21-427d-a23a-50082363610d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div[2]/div[2]/input</value>
      <webElementGuid>1f610ee1-d2d6-4d21-b2e9-e6377de4f174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'ag-1732-input' and @placeholder = 'Search...']</value>
      <webElementGuid>5dfef186-f0be-4280-be26-057caa3a1f5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
