<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name_w-full px-3 py-2 border-b border_53872a_1_2_3_4_5_6</name>
   <tag></tag>
   <elementGuidId>8aabe7c5-ec08-445b-8421-aca937f74f35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='TEstta']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=main >> internal:role=textbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d6b750ae-5668-4e4b-b573-3671711ecd80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>35cab3c3-9b0c-46cd-ac57-c9b3b3f5f298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full px-3 py-2 border-b border-gray-800 focus:outline-none focus:border-teal-500 mb-2</value>
      <webElementGuid>f7990b77-d034-41d4-b9e5-521c0b264f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>TEstta</value>
      <webElementGuid>2f70878d-e53e-4716-9825-7278487c2a9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/div[@class=&quot;w-full h-[calc(100vh-4rem)] overflow-hidden&quot;]/div[@class=&quot;w-full h-full&quot;]/div[@class=&quot;max-w-full bg-background-primary font-roboto&quot;]/div[@class=&quot;flex justify-between items-center px-5 py-8&quot;]/div[@class=&quot;fixed inset-0 bg-black bg-opacity-50  flex items-center justify-center z-50&quot;]/div[@class=&quot;bg-white rounded-md shadow-lg w-full max-w-4xl&quot;]/div[@class=&quot;p-8 h-[400px] flex flex-col&quot;]/div[@class=&quot;overflow-y-auto flex-grow scrollbar-thin scrollbar-thumb-gray-300 scrollbar-track-gray-100&quot;]/div[@class=&quot;max-w-2xl mx-auto p-4 bg-white rounded&quot;]/div[1]/input[@class=&quot;w-full px-3 py-2 border-b border-gray-800 focus:outline-none focus:border-teal-500 mb-2&quot;]</value>
      <webElementGuid>90995ff7-38ae-4fdb-a81b-72e0c423eada</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='TEstta']</value>
      <webElementGuid>bdcacfa3-7947-4108-ac3d-9c59ba0adde7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div[2]/div/div/div[2]/div/div[2]/div[2]/div/div/input</value>
      <webElementGuid>257763ce-3e4c-4ed1-bdc5-a976d65b910f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>973983a6-238f-4e5d-9b20-1334a6651dca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>a960eaa6-3f9a-4359-920d-488744aba442</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
