<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name_w-full px-3 py-2 border-b border_53872a_1_2</name>
   <tag></tag>
   <elementGuidId>b3ef2536-4121-440d-838e-9fbad536462c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='pr']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=main >> internal:role=textbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d5780e16-f6b5-4637-a9a3-5eb1f3017051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>507ea02b-977c-49a4-8602-51675dccbd91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full px-3 py-2 border-b border-gray-800 focus:outline-none focus:border-teal-500 mb-2</value>
      <webElementGuid>6c786c04-49ad-40b1-bc9d-81b3aca8bfa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>pr</value>
      <webElementGuid>600db39d-0f8b-45ee-b2fb-22b4c275f021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/div[@class=&quot;w-full h-[calc(100vh-4rem)] overflow-hidden&quot;]/div[@class=&quot;w-full h-full&quot;]/div[@class=&quot;max-w-full bg-background-primary font-roboto&quot;]/div[@class=&quot;flex justify-between items-center px-5 py-8&quot;]/div[@class=&quot;fixed inset-0 bg-black bg-opacity-50  flex items-center justify-center z-50&quot;]/div[@class=&quot;bg-white rounded-md shadow-lg w-full max-w-4xl&quot;]/div[@class=&quot;p-8 h-[400px] flex flex-col&quot;]/div[@class=&quot;overflow-y-auto flex-grow scrollbar-thin scrollbar-thumb-gray-300 scrollbar-track-gray-100&quot;]/div[@class=&quot;max-w-2xl mx-auto p-4 bg-white rounded&quot;]/div[1]/input[@class=&quot;w-full px-3 py-2 border-b border-gray-800 focus:outline-none focus:border-teal-500 mb-2&quot;]</value>
      <webElementGuid>4fe654e9-63ec-4840-91b6-694e2ebb3a81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='pr']</value>
      <webElementGuid>a4e79acd-d501-4604-9192-ac848a017e7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div[2]/div/div/div[2]/div/div[2]/div[2]/div/div/input</value>
      <webElementGuid>cae15c1f-ea13-49a6-a463-53f016d5c3f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>829e16ad-d5f7-47a0-bdd4-77b657abbdac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>17d310f5-1f24-42d1-8c39-aaaf6e3d5978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='TE']</value>
      <webElementGuid>92ff6562-41ff-4306-bed0-e311d8bbf568</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
