<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name_w-full px-3 py-2 border-b border_53872a_1_2_3</name>
   <tag></tag>
   <elementGuidId>4dad992e-c480-4238-bacd-c34ba06542e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='pri']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=main >> internal:role=textbox</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4d5c0f85-af76-4896-af09-f4cd5de70e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fcd60880-3015-46ce-bb04-c44e8f059128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full px-3 py-2 border-b border-gray-800 focus:outline-none focus:border-teal-500 mb-2</value>
      <webElementGuid>a6ad3c14-5df9-4ff0-bcbb-db7efc0b3e66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>pri</value>
      <webElementGuid>89acacaa-9e37-4fcd-8b6d-857470077d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/div[@class=&quot;w-full h-[calc(100vh-4rem)] overflow-hidden&quot;]/div[@class=&quot;w-full h-full&quot;]/div[@class=&quot;max-w-full bg-background-primary font-roboto&quot;]/div[@class=&quot;flex justify-between items-center px-5 py-8&quot;]/div[@class=&quot;fixed inset-0 bg-black bg-opacity-50  flex items-center justify-center z-50&quot;]/div[@class=&quot;bg-white rounded-md shadow-lg w-full max-w-4xl&quot;]/div[@class=&quot;p-8 h-[400px] flex flex-col&quot;]/div[@class=&quot;overflow-y-auto flex-grow scrollbar-thin scrollbar-thumb-gray-300 scrollbar-track-gray-100&quot;]/div[@class=&quot;max-w-2xl mx-auto p-4 bg-white rounded&quot;]/div[1]/input[@class=&quot;w-full px-3 py-2 border-b border-gray-800 focus:outline-none focus:border-teal-500 mb-2&quot;]</value>
      <webElementGuid>4cf8fe88-1326-4c72-a2cc-f68b64effd3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='pri']</value>
      <webElementGuid>5b5532cd-59d7-4ce4-af0d-9ab3cfcc8603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div[2]/div/div/div[2]/div/div[2]/div[2]/div/div/input</value>
      <webElementGuid>6c26d627-e5d0-4b07-a2b3-889205a9ec5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>74347a9d-9328-4768-ab2b-d7d7a9de640e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>f17a2146-c396-4a4b-8248-d27cb3462ca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='TEs']</value>
      <webElementGuid>3960e7c9-d04f-476e-87b4-387cbcbabb29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
