<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Location_ag-1911-input</name>
   <tag></tag>
   <elementGuidId>cddfc070-b758-468d-9578-09962f6b5c59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ag-1911-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ag-1911-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ag-1911-input</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b348c0b1-f734-47f8-b3d4-2e1786502ef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>eInput</value>
      <webElementGuid>9008690b-2371-4d7e-9dec-5a5120afa585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ag-input-field-input ag-checkbox-input</value>
      <webElementGuid>5a1ac5ae-d601-4ca1-aebd-2767996bf8ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0f113ad9-7aa5-4f9e-a653-f6c158ccf903</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ag-1911-input</value>
      <webElementGuid>4a35da65-4524-4b92-9d5a-768785b2b7b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>3e5e96e6-a655-4af6-9c04-148f1936f32b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Press Space to toggle row selection (unchecked)</value>
      <webElementGuid>b0bc44cb-c3a8-4e8f-a096-b772057d5faf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ag-1911-input&quot;)</value>
      <webElementGuid>ce62ab7c-068f-4d53-b75a-1c66d6f0131c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ag-1911-input']</value>
      <webElementGuid>53bd699a-5843-4e7d-844f-3d07d1ad7d09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div[2]/div/div[2]/div[2]/div/div[3]/div[2]/div[2]/div[4]/div/div/div[5]/div/div/div/div/div[2]/input</value>
      <webElementGuid>55605ff0-0501-44de-a457-64beacbd14c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div/div[2]/input</value>
      <webElementGuid>337745eb-63ce-488a-8e37-ae7eb09eee54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'ag-1911-input']</value>
      <webElementGuid>251d4b34-3093-430c-a8c9-39cfc5105217</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
