<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Display</name>
   <tag></tag>
   <elementGuidId>03ff1c9e-f9ab-4c02-b135-fb070a6135fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/main/div/div[2]/div/div/div/div[2]/div/div[2]/label[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Display&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>feb90b25-fac2-4b39-9216-609115ce9ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex items-center gap-2 px-3 py-2 hover:bg-gray-100 cursor-pointer</value>
      <webElementGuid>090f93dd-91cf-4392-9f0c-c870d4a4d879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Display</value>
      <webElementGuid>715dc360-c2ac-490f-8a41-b79dce9f4cc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/main[1]/div[@class=&quot;w-full h-full overflow-hidden&quot;]/div[@class=&quot;w-full h-full&quot;]/div[@class=&quot;flex flex-col&quot;]/div[@class=&quot;bg-background-primary flex flex-col md:flex-row items-start gap-2&quot;]/div[@class=&quot;flex flex-col gap-4 p-2&quot;]/div[@class=&quot;flex flex-col gap-1 relative&quot;]/div[@class=&quot;relative&quot;]/div[@class=&quot;z-10 absolute top-full left-0 w-44 bg-white border border-gray-300 rounded-md shadow-md mt-1&quot;]/label[@class=&quot;flex items-center gap-2 px-3 py-2 hover:bg-gray-100 cursor-pointer&quot;]</value>
      <webElementGuid>db2282a7-e6b8-4d11-88bf-f503c6681d3a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div[2]/div/div/div/div[2]/div/div[2]/label[3]</value>
      <webElementGuid>461d9e65-7fa9-4cd8-a17d-133d6fd4ee0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inventory'])[2]/following::label[1]</value>
      <webElementGuid>2aaa2982-466d-4e11-993d-e5cab3d36c1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All'])[2]/following::label[2]</value>
      <webElementGuid>c8f0f5f4-336d-4979-a1f7-4f29196ca974</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Summary'])[1]/preceding::label[1]</value>
      <webElementGuid>facf401a-c782-4c16-a6fd-3bd1ac9d99e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date Range'])[1]/preceding::label[1]</value>
      <webElementGuid>b58d3e9c-65ac-4a0d-ab94-4935eb5e3a76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Display']/parent::*</value>
      <webElementGuid>5cabd8b3-c3ae-4127-ae3d-1534da748dfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[3]</value>
      <webElementGuid>83818dc7-7ff3-44c9-bf7b-42a80e6cce88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Display' or . = 'Display')]</value>
      <webElementGuid>53610597-0c9a-42be-9a82-c47c7f54c942</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
