<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select a packageEssentialEssential, _f74aa2</name>
   <tag></tag>
   <elementGuidId>116c2329-6621-4e1c-b2ea-18ba1429f9e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='subscriptionPackage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;subscriptionPackage&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>select[name=&quot;subscriptionPackage&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>80d1e61a-5184-4510-af3f-a5cb9fa6e356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>subscriptionPackage</value>
      <webElementGuid>201a6f75-3421-4009-ba22-2dcc98c8c506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full p-3 border rounded-md bg-gray-50 </value>
      <webElementGuid>6d380b18-e3d5-4d29-960d-fe143b122e3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select a packageEssentialEssential, DisplayEssential, TransformEssential, Transform, DisplayAdvancedAdvanced, DisplayAdvanced, TransformAdvanced, Display, TransformDisplayDisplay, Transform</value>
      <webElementGuid>f89f5516-f935-4dfb-846d-6cbe91821f18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;min-h-screen&quot;]/main[1]/div[@class=&quot;bg-gray-50 w-full h-[calc(100vh-4rem)] flex flex-col items-center&quot;]/div[@class=&quot;fixed inset-0 z-50 flex items-center justify-center&quot;]/div[@class=&quot;relative bg-background-primary rounded-sm shadow-lg w-full max-w-6xl mx-4 min-h-[92vh] overflow-y-auto&quot;]/div[@class=&quot;p-6&quot;]/div[@class=&quot;border-b&quot;]/div[@class=&quot;grid grid-cols-1 md:grid-cols-2 gap-8 max-h-[63vh] overflow-y-auto p-6&quot;]/div[@class=&quot;space-y-6&quot;]/div[4]/select[@class=&quot;w-full p-3 border rounded-md bg-gray-50&quot;]</value>
      <webElementGuid>1763bb42-3eac-49fe-9762-2edc8c5c28bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='subscriptionPackage']</value>
      <webElementGuid>c9d61c01-b17b-45b5-a2de-1a3a438fe63a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/main/div/div[3]/div[2]/div[2]/div[2]/div/div[2]/div[4]/select</value>
      <webElementGuid>81ba9b4f-bfd6-463d-a58e-a99357cfe3b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[12]/following::select[1]</value>
      <webElementGuid>c41f163d-0091-422b-96bc-faebe2b5ba1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Name'])[1]/preceding::select[1]</value>
      <webElementGuid>c8eea291-4c38-4bd3-b69d-9fdee60ae6de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Address'])[1]/preceding::select[1]</value>
      <webElementGuid>b7313c1e-4607-49d2-bc2f-a0bfc6fcf84b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/select</value>
      <webElementGuid>5a4b2a1c-831c-42f6-a220-951bb10d81af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'subscriptionPackage' and (text() = 'Select a packageEssentialEssential, DisplayEssential, TransformEssential, Transform, DisplayAdvancedAdvanced, DisplayAdvanced, TransformAdvanced, Display, TransformDisplayDisplay, Transform' or . = 'Select a packageEssentialEssential, DisplayEssential, TransformEssential, Transform, DisplayAdvancedAdvanced, DisplayAdvanced, TransformAdvanced, Display, TransformDisplayDisplay, Transform')]</value>
      <webElementGuid>c2b01c35-8c46-40b4-9520-be6c7a78d9c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
