<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Drag here to set column labels_ag-icon_9d49b7</name>
   <tag></tag>
   <elementGuidId>1d2ef882-f44c-406b-92fd-89c4f58d9653</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/main/div/div[2]/div[2]/div/div[3]/div[2]/div[2]/div/div[2]/div/div/div/div[3]/div/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.ag-icon.ag-icon-filter</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.ag-header-icon > .ag-icon >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>34b3590f-5027-43be-9c7b-da26b0fe0d69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ag-icon ag-icon-filter</value>
      <webElementGuid>3a05ccd4-701a-44db-95ee-2e7549531690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>unselectable</name>
      <type>Main</type>
      <value>on</value>
      <webElementGuid>f831aba9-c3f2-4350-b950-c2db0fe03694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>8c55bbeb-c5fd-4a28-804d-67ec32abe402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;min-h-screen&quot;]/main[1]/div[@class=&quot;bg-gray-50 w-full h-[calc(100vh-4rem)] flex flex-col items-center&quot;]/div[@class=&quot;bg-background-primary flex flex-col h-[calc(100vh-100px)] flex flex-col w-[95%] p-5 mt-5 mb-10&quot;]/div[@class=&quot;ag-theme-alpine&quot;]/div[1]/div[@class=&quot;ag-root-wrapper ag-ltr ag-layout-normal&quot;]/div[@class=&quot;ag-root-wrapper-body ag-focus-managed ag-layout-normal&quot;]/div[@class=&quot;ag-root ag-unselectable ag-layout-normal&quot;]/div[@class=&quot;ag-header ag-pivot-off ag-header-allow-overflow&quot;]/div[@class=&quot;ag-header-viewport&quot;]/div[@class=&quot;ag-header-container&quot;]/div[@class=&quot;ag-header-row ag-header-row-column&quot;]/div[@class=&quot;ag-header-cell ag-column-first ag-header-cell-sortable ag-focus-managed ag-header-active&quot;]/div[@class=&quot;ag-header-cell-comp-wrapper&quot;]/div[@class=&quot;ag-cell-label-container&quot;]/span[@class=&quot;ag-header-icon ag-header-cell-filter-button&quot;]/span[@class=&quot;ag-icon ag-icon-filter&quot;]</value>
      <webElementGuid>48cc8a80-5166-4d79-8869-5dc53efb3f40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/main/div/div[2]/div[2]/div/div[3]/div[2]/div[2]/div/div[2]/div/div/div/div[3]/div/span/span</value>
      <webElementGuid>32b4e1c6-f236-4f5c-861b-041fecde4de8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/span</value>
      <webElementGuid>b443fd98-6fd5-4a18-bd76-f54cc7d38f42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myGrid']/div/div[3]/div[2]/div[2]/div/div[2]/div/div/div/div[3]/div/span/span</value>
      <webElementGuid>f008d318-ba1f-4add-8cb1-7c407e63ac7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[3]/div/span/span</value>
      <webElementGuid>8e661db2-fe77-4015-8187-dbc5943eeb00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
