<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_English - Change Language</name>
   <tag></tag>
   <elementGuidId>a99bd404-5b44-45db-bd2d-52ed4258b42d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.inline-flex.items-center.text-teal-600</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;English - Change Language?&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>787e6759-19d5-4322-a3b8-c46f88ff94b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>350a4f3c-c096-4f20-baba-fedf1371a0c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center text-teal-600</value>
      <webElementGuid>3c101272-dc9d-407b-889a-7a95f3f1cedf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>English - Change Language?</value>
      <webElementGuid>59b36f97-170b-484f-bff0-56192502f83e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;flex h-screen bg-white&quot;]/div[@class=&quot;w-1/2 flex flex-col justify-center items-center p-20&quot;]/div[@class=&quot;w-full max-w-md text-center&quot;]/div[@class=&quot;mb-10 mt-10 text-center&quot;]/button[@class=&quot;inline-flex items-center text-teal-600&quot;]</value>
      <webElementGuid>f9554739-7db9-438d-bc97-e99b5a152160</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>f4863f6a-2a7e-4173-af4a-77d3d1f6e587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/div/div[2]/button</value>
      <webElementGuid>abfa285c-c6e8-4112-95e5-1013096db5cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::button[1]</value>
      <webElementGuid>6b4d79c4-23a2-425b-a39e-48cafffe8570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Username'])[1]/following::button[2]</value>
      <webElementGuid>ad72a0aa-9b6e-4f9b-80fc-197d5a1e740d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>8ab60242-e036-4c64-8e6d-b8a7b36f77d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'English - Change Language?' or . = 'English - Change Language?')]</value>
      <webElementGuid>7cc16314-b45c-48f8-b653-a2e3a805204e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
