<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Users</name>
   <tag></tag>
   <elementGuidId>ff92faa0-4093-4ce1-94bb-8b48c738b19b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div/div[2]/button[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Users&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4b848e8c-1c10-40c9-a709-ef2911343c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-4 rounded-t transition-colors duration-200 font-medium text-sm hover:bg-white hover:h-[50px] hover:text-black rounded-tl-[0.8em] rounded-tr-[0.8em]</value>
      <webElementGuid>e0f2b116-9d71-410a-9e86-2d7d340d44e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Users</value>
      <webElementGuid>fc5f07b5-f943-4e64-9007-d763b362313a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;min-h-screen&quot;]/div[@class=&quot;sticky z-50 top-0 w-full bg-[#008b8b] text-text-white font-semibold&quot;]/div[@class=&quot;flex items-center justify-between px-6 min-h-[60px]&quot;]/div[@class=&quot;flex justify-start max-w-[653px] gap-1 items-center flex-1 mt-[10px]&quot;]/button[@class=&quot;px-4 rounded-t transition-colors duration-200 font-medium text-sm hover:bg-white hover:h-[50px] hover:text-black rounded-tl-[0.8em] rounded-tr-[0.8em]&quot;]</value>
      <webElementGuid>0ac1d551-4adb-4114-a125-963687661a69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div[2]/button[2]</value>
      <webElementGuid>7accc0e5-a177-4c7a-aa06-52c5d02dd1b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Management'])[1]/following::button[1]</value>
      <webElementGuid>c04087a8-8818-4f7e-98b6-0ca4273fb9b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sites'])[1]/preceding::button[1]</value>
      <webElementGuid>7e9a2694-f21f-49d3-bffe-5874d99ca6eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Products'])[1]/preceding::button[2]</value>
      <webElementGuid>8c05ce52-0e6e-4f85-b47a-7a2636d6e600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Users']/parent::*</value>
      <webElementGuid>dae32650-b2c0-4802-adcd-90704d64f69a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>d8ecd1bd-e421-4f5c-8c6f-fe0c32e02f79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Users' or . = 'Users')]</value>
      <webElementGuid>e690ed86-b61f-496d-8dfa-162e5fb30b75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
