<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Configurations</name>
   <tag></tag>
   <elementGuidId>8c4d3411-1ab3-4503-9a02-ca5ed9a3f17b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div/div/div[2]/button[6]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Configurations&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>def4261a-fb26-4df3-880a-50c9b60bc43b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-4 rounded-t transition-colors duration-200 font-medium text-sm hover:bg-white hover:h-[50px] hover:text-black rounded-tl-[0.8em] rounded-tr-[0.8em]</value>
      <webElementGuid>b0939c20-d750-4ff9-84d2-cd3c2fd2bf85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Configurations</value>
      <webElementGuid>0e245dff-1c3c-407e-9a83-4d700252fa08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;min-h-screen&quot;]/div[@class=&quot;sticky z-50 top-0 w-full bg-[#008b8b] text-text-white font-semibold&quot;]/div[@class=&quot;flex items-center justify-between px-6 min-h-[60px]&quot;]/div[@class=&quot;flex justify-start max-w-[653px] gap-1 items-center flex-1 mt-[10px]&quot;]/button[@class=&quot;px-4 rounded-t transition-colors duration-200 font-medium text-sm hover:bg-white hover:h-[50px] hover:text-black rounded-tl-[0.8em] rounded-tr-[0.8em]&quot;]</value>
      <webElementGuid>e0f609b6-eea5-4da5-b096-2340266530b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div/div/div[2]/button[6]</value>
      <webElementGuid>501cf526-74b6-4dc1-95eb-d20b6dd66442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stock Targets'])[1]/following::button[1]</value>
      <webElementGuid>bcadaa07-e373-4e42-87fa-83dea0e23c5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Products'])[1]/following::button[2]</value>
      <webElementGuid>88dfffc7-d765-4b49-8106-2cd690977cf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CS'])[1]/preceding::button[1]</value>
      <webElementGuid>047906d0-6738-4c22-98cc-bb38e2146f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload Stock Targets'])[1]/preceding::button[1]</value>
      <webElementGuid>756218fe-9e30-4638-892d-0c940bcb2639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Configurations']/parent::*</value>
      <webElementGuid>f96cd501-22d6-4fd8-ba49-9d33cac6a346</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[6]</value>
      <webElementGuid>6c9bae92-04d0-45ca-b1ee-da2c9e29bcf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Configurations' or . = 'Configurations')]</value>
      <webElementGuid>58292a39-802a-4fc6-8391-643674ed56cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
