<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_(Select All)_ag-403-input</name>
   <tag></tag>
   <elementGuidId>c4724706-ca84-4bee-87b1-bed30a8e9efe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ag-403-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ag-403-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;(Select All)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>604c02b4-d621-413b-abdf-7fa7a11700a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>eInput</value>
      <webElementGuid>9ee1b91e-e479-4491-a9bd-0cd95d65a0dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ag-input-field-input ag-checkbox-input</value>
      <webElementGuid>3efc7020-fb38-4913-943b-ff3ca0d3688e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>fc44ed98-d2d0-4066-b22c-de0d75a6e79e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ag-403-input</value>
      <webElementGuid>215d0e01-c0cc-4924-bc9d-527d9728fc14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>feacdf7e-a16e-4a14-b57e-f63103f35012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>ag-403-label</value>
      <webElementGuid>60b4a28a-e248-4691-8885-f6fd988fcb42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ag-403-input&quot;)</value>
      <webElementGuid>1e7b1fb1-c5ea-48e2-9d83-29679dddfd52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ag-403-input']</value>
      <webElementGuid>23dc992a-1b0f-4a6e-ac27-836fa1877743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/main/div/div[2]/div/div[2]/div/div/div/div/div[3]/div[6]/div/div/form/div/div/div[4]/div/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>69cb1d28-89c9-4290-a0ab-0afe70f38cc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/div/div/div/div[2]/input</value>
      <webElementGuid>cb3125c6-3b9b-483a-a677-88a5e2e4b33c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'ag-403-input']</value>
      <webElementGuid>51d57ca7-a544-424b-a518-d5fc38330aa0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
