<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_login</name>
   <tag></tag>
   <elementGuidId>9da8a36b-c132-45a1-8a6c-235cba396c22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#kc-login</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='kc-login']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;LogIn&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ddf9ad04-9aeb-46ac-abca-81ce06e43568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>7a33cef1-4aea-4a7a-8a7e-ce9a9d4f82cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pf-c-button pf-m-primary pf-m-block btn-lg</value>
      <webElementGuid>83a0572c-fea8-4e09-836e-b9445efebe59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>login</value>
      <webElementGuid>ce03ea2c-2e88-4d2f-9a4f-d8356ac3453b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>kc-login</value>
      <webElementGuid>1300ef4f-19c8-4249-b4e3-7ac542fa33c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e453b3ba-acd1-4946-bd99-acca293551be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>LogIn</value>
      <webElementGuid>238f2525-4d0f-46ba-9887-c10a7e8c18d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kc-login&quot;)</value>
      <webElementGuid>ccd01034-20c4-42da-8e66-808782c622d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='kc-login']</value>
      <webElementGuid>b550dd95-ee50-431a-8ef0-96f2bde5163e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kc-form-buttons']/input[2]</value>
      <webElementGuid>f48f28aa-1eeb-4a31-9471-0cd33522db37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>74c91f87-5a26-41b3-9690-30d183bacfcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'login' and @id = 'kc-login' and @type = 'submit']</value>
      <webElementGuid>fb16abf0-73f9-4440-8760-84098f12fb23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
