<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Drag here to set column labels_ag-143-input</name>
   <tag></tag>
   <elementGuidId>16084d76-bc97-4005-a975-c662a61ca91c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ag-143-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#ag-143-input</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e14a9c11-d55c-454e-92b8-b51928e539c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ref</name>
      <type>Main</type>
      <value>eInput</value>
      <webElementGuid>7ede4eed-1f0f-45db-b213-7d472eeb7181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ag-input-field-input ag-checkbox-input</value>
      <webElementGuid>823e59b1-4c04-47c8-b0a0-48f10e945213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>f42fc617-da4b-43d7-a39f-c0e4f9acdfc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ag-143-input</value>
      <webElementGuid>7fa3d15d-50e5-4018-87c2-dafdec2de581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>236593bb-fd7b-4ec9-acbc-5782d3c3dd19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Press Space to toggle all rows selection (unchecked)</value>
      <webElementGuid>fa447760-a41e-4bca-a0d9-ace00dbb7338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ag-143-input&quot;)</value>
      <webElementGuid>b8ac0e86-6ffb-4abe-b6f8-e0a242ed858c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ag-143-input']</value>
      <webElementGuid>ea4be1f2-fade-44ca-aae7-0045f810abd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/main/div/div[2]/div/div[2]/div/div/div/div/div[3]/div[2]/div[2]/div/div[2]/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>c0b21e05-dee4-4d5f-b5e8-473a69758615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>39177719-f063-4c52-b6ee-3e632a4c60e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'ag-143-input']</value>
      <webElementGuid>12835ab0-a1f3-41d7-8f07-62c27828a0a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
